/**
 * engine.test.js — tests for LinxiconEngine and loadEmbeddings.
 *
 * Uses sample.bin (generated by scripts/create-sample.js) for loader tests.
 * Engine logic tests build a minimal in-memory embeddings Map directly so
 * they don't depend on any file.
 *
 * Run: node test/engine.test.js
 */

import { strict as assert } from 'node:assert';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { existsSync } from 'node:fs';
import { LinxiconEngine } from '../src/engine.js';
import { loadEmbeddings }  from '../src/loader.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err) {
    console.error(`  ✗ ${name}`);
    console.error(`    ${err.message}`);
    failed++;
  }
}

async function asyncTest(name, fn) {
  try {
    await fn();
    console.log(`  ✓ ${name}`);
    passed++;
  } catch (err) {
    console.error(`  ✗ ${name}`);
    console.error(`    ${err.message}`);
    failed++;
  }
}

// ---------------------------------------------------------------------------
// Build a minimal synthetic embeddings map for engine tests.
// Two clusters of words; within-cluster similarity is high, cross is low.
// ---------------------------------------------------------------------------

function makeVec(dims, signalDims, signalStrength = 2.0, noise = 0.1) {
  const raw = new Float32Array(dims);
  for (const d of signalDims) raw[d] = signalStrength + (Math.random() - 0.5) * noise;
  for (let d = 0; d < dims; d++) {
    if (!signalDims.includes(d)) raw[d] = (Math.random() - 0.5) * 0.1;
  }
  let mag = 0;
  for (const v of raw) mag += v * v;
  mag = Math.sqrt(mag);
  for (let i = 0; i < raw.length; i++) raw[i] /= mag;
  return raw;
}

function computeStats(vecs) {
  const n = vecs.length;
  return vecs.map((v, i) => {
    const sims = vecs.filter((_, j) => j !== i).map(u => {
      let s = 0;
      for (let k = 0; k < v.length; k++) s += v[k] * u[k];
      return s;
    });
    const mean = sims.reduce((a, b) => a + b) / sims.length;
    const variance = sims.reduce((a, b) => a + (b - mean) ** 2, 0) / (sims.length - 1);
    return { mean, std: Math.sqrt(variance) };
  });
}

const DIMS = 20;

// Cluster A: signal in dims 0-4
const clusterAWords = ['music', 'song', 'melody', 'rhythm', 'beat'];
const clusterAVecs  = clusterAWords.map(() => makeVec(DIMS, [0, 1, 2, 3, 4]));

// Cluster B: signal in dims 10-14
const clusterBWords = ['science', 'physics', 'chemistry', 'biology', 'research'];
const clusterBVecs  = clusterBWords.map(() => makeVec(DIMS, [10, 11, 12, 13, 14]));

const allWords = [...clusterAWords, ...clusterBWords];
const allVecs  = [...clusterAVecs, ...clusterBVecs];
const allStats = computeStats(allVecs);

const testEmbeddings = new Map();
for (let i = 0; i < allWords.length; i++) {
  testEmbeddings.set(allWords[i], {
    vec:  allVecs[i],
    mean: allStats[i].mean,
    std:  allStats[i].std,
  });
}

// ---------------------------------------------------------------------------
// Tests: LinxiconEngine
// ---------------------------------------------------------------------------

console.log('\nLinxiconEngine — vocabulary');

test('hasWord returns true for known words', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  assert(engine.hasWord('music'));
  assert(engine.hasWord('MUSIC'));  // case-insensitive
  assert(!engine.hasWord('xyzzy'));
});

test('cosineSimilarity returns null for unknown words', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  assert.equal(engine.cosineSimilarity('music', 'unknown'), null);
});

test('cosineSimilarity is higher within cluster than across clusters', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const sameSim  = engine.cosineSimilarity('music', 'song');
  const crossSim = engine.cosineSimilarity('music', 'science');
  assert(sameSim > crossSim, `Expected same-cluster (${sameSim.toFixed(3)}) > cross-cluster (${crossSim.toFixed(3)})`);
});

console.log('\nLinxiconEngine — createGame');

test('createGame throws for unknown start word', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  assert.throws(() => engine.createGame('unknown', 'music'));
});

test('createGame throws when start === target', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  assert.throws(() => engine.createGame('music', 'music'));
});

test('createGame creates board with two words and no edges', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const state = engine.createGame('music', 'science');
  assert.equal(state.words[0], 'music');
  assert.equal(state.words[1], 'science');
  assert.equal(state.words.length, 2);
  assert.equal(state.edges.length, 0);   // no edges on creation, even if words are close
  assert.equal(state.status, 'active');
});

test('pairSimilarity identifies trivial pairs', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const same  = engine.pairSimilarity('music', 'song');   // same cluster → trivial
  const cross = engine.pairSimilarity('music', 'science'); // diff clusters → not trivial
  assert(same  && same.isTrivial,  `Expected music↔song to be trivial, sim=${same?.similarity.toFixed(3)} thresh=${same?.threshold.toFixed(3)}`);
  assert(cross && !cross.isTrivial, `Expected music↔science to not be trivial`);
  assert(typeof cross.similarity === 'number');
  assert(typeof cross.threshold  === 'number');
});

console.log('\nLinxiconEngine — addWord');

test('addWord rejects unknown word', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const state  = engine.createGame('music', 'science');
  const { result } = engine.addWord(state, 'xyzzy');
  assert.equal(result.accepted, false);
  assert.equal(result.reason, 'unknown_word');
});

test('addWord rejects word already on board', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const state  = engine.createGame('music', 'science');
  const { result } = engine.addWord(state, 'music');
  assert.equal(result.accepted, false);
  assert.equal(result.reason, 'already_on_board');
});

test('addWord accepts valid word and adds to board', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const state  = engine.createGame('music', 'science');
  const { state: s2, result } = engine.addWord(state, 'song');
  assert(result.accepted);
  assert(s2.words.includes('song'));
  assert.equal(s2.words.length, 3);
});

test('addWord connects word to same-cluster neighbors', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const state  = engine.createGame('music', 'science');
  const { result } = engine.addWord(state, 'song');
  // 'song' is in the same cluster as 'music' — should form an edge
  const edgeWords = result.newEdges.map(([a, b]) => [a, b]);
  const hasMusicSong = edgeWords.some(([a, b]) => (a === 'music' || b === 'music'));
  assert(hasMusicSong, `Expected edge to 'music' but got: ${JSON.stringify(result.newEdges)}`);
});

test('addWord does not connect word to cross-cluster words', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const state  = engine.createGame('music', 'science');
  const { result } = engine.addWord(state, 'song');
  const edgeWords = result.newEdges.map(([a, b]) => [a, b]);
  const hasScienceSong = edgeWords.some(([a, b]) => a === 'science' || b === 'science');
  assert(!hasScienceSong, `Unexpected edge to 'science': ${JSON.stringify(result.newEdges)}`);
});

test('addWord returns won=false when path does not exist yet', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  let state = engine.createGame('music', 'science');
  const { result } = engine.addWord(state, 'song');
  assert.equal(result.won, false);
});

console.log('\nLinxiconEngine — win condition');

test('checkWin detects connected path (BFS correctness)', () => {
  // Directly construct a state with edges already in place to test BFS win detection
  // without coupling to threshold logic.
  const engine = new LinxiconEngine(testEmbeddings);
  const connected = {
    id: 'test',
    startWord: 'music',
    targetWord: 'science',
    words: ['music', 'science', 'melody'],
    edges: [[0, 2, 0.9], [1, 2, 0.9]],  // music↔melody and science↔melody
    status: 'active',
    adaptiveK: 1.0,
  };
  assert(engine.checkWin(connected), 'Should be connected via melody');
  const path = engine.shortestPath(connected);
  assert.deepEqual(path, ['music', 'melody', 'science']);
});

test('addWord causes win when it bridges both endpoints', () => {
  // Use very negative adaptiveK (threshold = mean - 2*std → very low) so that
  // any word with moderate similarity to both sides forms edges.
  // This tests addWord's win detection path, not threshold calibration.
  const engine = new LinxiconEngine(testEmbeddings, { adaptiveK: -2.0 });
  let state = engine.createGame('music', 'science', { adaptiveK: -2.0 });
  const { state: s2, result } = engine.addWord(state, 'melody');
  // At k=-2.0, melody (cluster A) connects to music AND, because threshold is
  // extremely low, likely also to science — or at minimum music connects via state.
  assert(result.accepted);
  // Whether won depends on the vectors; what matters is won===true iff a path exists.
  assert.equal(result.won, engine.checkWin(s2));
  assert.equal(s2.status, result.won ? 'won' : 'active');
});

test('checkWin returns false when not connected', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const state  = engine.createGame('music', 'science');
  assert.equal(engine.checkWin(state), false);
});

console.log('\nLinxiconEngine — path and metrics');

test('shortestPath returns null when not connected', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const state  = engine.createGame('music', 'science');
  assert.equal(engine.shortestPath(state), null);
});

test('getMetrics returns correct wordsOnBoard', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  let state = engine.createGame('music', 'science');
  assert.equal(engine.getMetrics(state).wordsOnBoard, 2);
  ({ state } = engine.addWord(state, 'song'));
  assert.equal(engine.getMetrics(state).wordsOnBoard, 3);
});

test('getMetrics shortestPathLength is null when unconnected', () => {
  const engine = new LinxiconEngine(testEmbeddings);
  const state  = engine.createGame('music', 'science');
  assert.equal(engine.getMetrics(state).shortestPathLength, null);
});

test('orphan word (no edges) is added to board', () => {
  // 'beat' is in cluster A, but if adaptiveK is very high, it may not connect even to 'music'
  // We test this indirectly: word is on board even with 0 edges
  const engine = new LinxiconEngine(testEmbeddings, { adaptiveK: 99 });
  const state  = engine.createGame('music', 'science');
  const { state: s2, result } = engine.addWord(state, 'beat');
  assert(result.accepted);
  assert(s2.words.includes('beat'));
  assert.equal(result.newEdges.length, 0, 'No edges expected at extreme adaptiveK');
});

// ---------------------------------------------------------------------------
// Tests: loadEmbeddings
// ---------------------------------------------------------------------------

console.log('\nloadEmbeddings');

const samplePath = resolve(__dirname, '../data/sample.bin');

// Auto-generate sample.bin if it doesn't exist (e.g. fresh clone)
if (!existsSync(samplePath)) {
  console.log('  sample.bin not found — generating...');
  await import('../scripts/create-sample.js');
  console.log('  done\n');
}

await asyncTest('loads sample.bin and returns a Map', async () => {
  const emb = await loadEmbeddings(samplePath);
  assert(emb instanceof Map);
  assert(emb.size > 0, 'Map should not be empty');
});

await asyncTest('each entry has vec, mean, std', async () => {
  const emb = await loadEmbeddings(samplePath);
  for (const [word, entry] of emb) {
    assert(entry.vec instanceof Float32Array, `${word}.vec not Float32Array`);
    assert(typeof entry.mean === 'number', `${word}.mean not a number`);
    assert(typeof entry.std  === 'number', `${word}.std not a number`);
    break; // check just the first entry
  }
});

await asyncTest('vectors are unit-length (pre-normalized)', async () => {
  const emb = await loadEmbeddings(samplePath);
  for (const [word, { vec }] of emb) {
    let mag = 0;
    for (const v of vec) mag += v * v;
    assert(Math.abs(Math.sqrt(mag) - 1.0) < 1e-4, `${word} vector magnitude ${Math.sqrt(mag).toFixed(4)} ≠ 1`);
    break;
  }
});

await asyncTest('sample contains expected cluster words', async () => {
  const emb = await loadEmbeddings(samplePath);
  for (const word of ['music', 'song', 'science', 'physics']) {
    assert(emb.has(word), `Expected word "${word}" in sample`);
  }
});

await asyncTest('same-cluster words have higher similarity than cross-cluster', async () => {
  const emb = await loadEmbeddings(samplePath);
  const engine = new LinxiconEngine(emb);
  const sameSim  = engine.cosineSimilarity('music', 'song');
  const crossSim = engine.cosineSimilarity('music', 'science');
  assert(sameSim > crossSim,
    `Expected same-cluster sim (${sameSim?.toFixed(3)}) > cross-cluster sim (${crossSim?.toFixed(3)})`);
});

// ---------------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------------

console.log(`\n${passed + failed} tests: ${passed} passed, ${failed} failed\n`);
if (failed > 0) process.exit(1);
